name: Bug Report
description: File a bug report to help us improve Permit
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - vincentvanbush

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: input
    id: permit-version
    attributes:
      label: Permit version
      description: What version of Permit are you using?
      placeholder: e.g., 0.3.0
    validations:
      required: true

  - type: input
    id: elixir-version
    attributes:
      label: Elixir/OTP version
      description: What version of Elixir and OTP are you using?
      placeholder: e.g., Elixir 1.17.0, OTP 27
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Set up authorization with...
        2. Define permissions as...
        3. Call the function...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: Please provide a minimal code example that demonstrates the issue
      render: elixir
      placeholder: |
        defmodule MyApp.Permissions do
          use Permit.Permissions

          def can(user) do
            # Your code here
          end
        end

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs/stack trace
      description: If applicable, add error logs or stack traces
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (database, Phoenix version, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all the requested information
          required: true
        - label: This is a bug report, not a feature request or question. For general questions, please use [Elixir Slack's Permit channel](https://elixir-lang.slack.com/archives/C091Q5S0GDU).
          required: true

