name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  MIX_ENV: test
  ImageOS: ubuntu22

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        elixir_version: ['1.12', '1.13', '1.14', '1.15', '1.16', '1.17']
        otp_version: ['24', '25', '26', '27']
        exclude:
          - elixir_version: '1.12'
            otp_version: '25'
          - elixir_version: '1.12'
            otp_version: '26'
          - elixir_version: '1.12'
            otp_version: '27'

          - elixir_version: '1.13'
            otp_version: '26'
          - elixir_version: '1.13'
            otp_version: '27'

          - elixir_version: '1.14'
            otp_version: '27'

          - elixir_version: '1.15'
            otp_version: '27'

          - elixir_version: '1.16'
            otp_version: '27'

          - elixir_version: '1.17'
            otp_version: '24'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir_version }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp_version }} # Define the OTP version [required]
      env:
        ImageOS: ubuntu22
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Set up Postgres
      run: |
       sudo apt-get update
       sudo apt-get install -y postgresql
       sudo service postgresql start
       sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
    - name: Install dependencies
      run: mix deps.get
    - name: Dialyzer
      run: MIX_ENV=test mix dialyzer
    - name: Credo
      run: MIX_ENV=test mix credo
    - name: Run tests
      run: mix coveralls.json
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
